### ISSUE TITLE
CSharp discord server invite

### ISSUE THREAD

**Issue by neon-sunset** [dubiousconst282/DistIL#34]
Recently, this library came up in a discussion in allow-unsafe-blocks channel on the main Discord server for C# and a few people from the JIT team got impressed and wanted to invite you there if you're interested:

https://discord.gg/csharp

(it's a public server - I'm posting here just to make sure)

**Comment by dubiousconst282** [comment]
Oh, I lurk there occasionally but I'm quite shy and don't usually talk much lol. Thanks anyway.
