### ISSUE TITLE
Add Nop Instruction and Pass

### ISSUE THREAD

**Issue by furesoft** [dubiousconst282/DistIL#47]
It is a good option for a debugger to use implicit sequence points by adding NOPs to the assembly. A pass could then remove them for a release buid (see [https://learn.microsoft.com/en-us/archive/blogs/rmbyers/debuggingmodes-ignoresymbolstoresequencepoints](https://learn.microsoft.com/en-us/archive/blogs/rmbyers/debuggingmodes-ignoresymbolstoresequencepoints))

**Comment by dubiousconst282** [comment]
Added in latest release.
