### ISSUE TITLE
Add DUP Instruction

### ISSUE THREAD

**Issue by furesoft** [dubiousconst282/DistIL#49]
Add the DUP intrinsic.

**Comment by dubiousconst282** [comment]
I'm not sure why this would be useful given the SSA IR has no notion of a evaluation stack as raw IL code does, what is the use case here?

**Comment by furesoft** [comment]
CIL completeness

**Comment by dubiousconst282** [comment]
I can't think of any way adding this as an intrinsic would make sense. We could add a few peepholes in ILAssembler to try and replace duplicate loads as a code size optimization, but I personally don't think that is worth the effort.
